name: framework-dbt.yml
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    name:
      " Python: ${{ matrix.python-version }} CrateDB: ${{ matrix.cratedb-version
      }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    services:
      cratedb:
        env:
          CRATE_HEAP_SIZE: 4g
        image: crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Acquire sources
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: x64
          cache: pip
          cache-dependency-path: "framework/dbt/basic/requirements.txt

            "
          python-version: ${{ matrix.python-version }}
      - name: Validate framework/dbt/basic
        run: "cd framework/dbt/basic

          pip install -r requirements.txt

          dbt run --debug

          dbt test --debug

          "
      - id: measurement-4
        name: Record Measurement After Validate framework/dbt/basic
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Validate framework/dbt/basic
          task: get-measurement
      - name: Validate framework/dbt/materialize
        run: "cd framework/dbt/materialize

          pip install -r requirements.txt

          dbt deps

          dbt run --debug

          dbt test --debug

          "
      - id: measurement-6
        name: Record Measurement After Validate framework/dbt/materialize
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Validate framework/dbt/materialize
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption7
          path: total_energy_consumption7.json
    strategy:
      fail-fast: false
      matrix:
        cratedb-version:
          - nightly
        os:
          - ubuntu-latest
        python-version:
          - "3.9"
          - "3.12"
