name: ml-automl.yml
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    name:
      " Python: ${{ matrix.python-version }} CrateDB: ${{ matrix.cratedb-version
      }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    services:
      cratedb:
        env:
          CRATE_HEAP_SIZE: 4g
        image: crate/crate:${{ matrix.cratedb-version }}
        ports:
          - 4200:4200
          - 5432:5432
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Acquire sources
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: x64
          cache: pip
          cache-dependency-path: "requirements.txt

            topic/machine-learning/automl/requirements.txt

            topic/machine-learning/automl/requirements-dev.txt

            "
          python-version: ${{ matrix.python-version }}
      - name: Install utilities
        run: "pip install -r requirements.txt

          "
      - id: measurement-4
        name: Record Measurement After Install utilities
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install utilities
          task: get-measurement
      - name: Validate topic/machine-learning/automl
        run: "ngr test --accept-no-venv topic/machine-learning/automl

          "
      - id: measurement-6
        name: Record Measurement After Validate topic/machine-learning/automl
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Validate topic/machine-learning/automl
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption22
          path: total_energy_consumption22.json
    strategy:
      fail-fast: false
      matrix:
        cratedb-version:
          - nightly
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
