name: testing-testcontainers-java.yml
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    name: ' Java: ${{ matrix.java-version }} CrateDB: ${{ matrix.cratedb-version }}
      on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Acquire sources
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: x64
          cache: pip
          cache-dependency-path: 'requirements.txt

            '
          python-version: '3.11'
      - name: Install utilities
        run: 'pip install -r requirements.txt

          '
      - id: measurement-4
        name: Record Measurement After Install utilities
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install utilities
          task: get-measurement
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Validate testing/testcontainers/java
        run: 'ngr test testing/testcontainers/java

          '
      - id: measurement-7
        name: Record Measurement After Validate testing/testcontainers/java
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Validate testing/testcontainers/java
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        cratedb-version:
          - nightly
        java-version:
          - '11'
          - '17'
          - '21'
        os:
          - ubuntu-latest
